name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm install -g surge
      - name: Get the last successful commit
        uses: rarmatei/last-successful-commit-action@v7
        id: last_successful_commit
        with:
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: 'deploy.yml'
      - run: npm run nx affected -- --target=deploy --base=${{ steps.last_successful_commit.outputs.commit_hash }}
        env:
          SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
